# This workflow performs the following: test
# - Database configuration
# - Provisioning Azure Services  
# - Create the spring-petclinic-AKS App on Docker
# - Create an Azure Container Registry 
# - Push your app to the container registry
# - Create a Kubernetes Cluster on AKS 
# - Deploy the image to your Kubernetes cluster
# - Verify your container image
#
# Secrets required to be in place:
# - AZURE_CREDENTIALS -

name: Build and Deploy Application
env:
  DEPLOYMENT_NAME: "petclinicaks"
  DEPLOYMENT_REGION: "eastus2"
  DEPLOYMENT_SUFFIX: "${{ github.run_id }}"
  RESOURCE_GROUP: "petclinicaks-rg-${{ github.run_id }}"
  ACR_NAME: "petclinicaksacr${{ github.run_number }}"
  CLUSTER_NAME: "aks-cluster-${{ github.run_id }}"
  VNET_NAME: "vnet-aks-${{ github.run_id }}"
  VM_NAME: "aks-vm-${{ github.run_id }}"
  FIREWALL_NAME: "aks-fw-${{ github.run_id }}"
  DB_SERVER_NAME: "petclinicaks-db-${{ github.run_id }}"

on:
  # Triggers the workflow on push events on the main branch
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'
      - '*.png'

  # We also want to be able to run this manually from Github
  workflow_dispatch:
jobs:
  hub_networking_AKS_Cluster:  # deploy Hub Networking Infra
     runs-on: ubuntu-latest
     steps:
     - name: 'Checkout GitHub Action'
       uses: actions/checkout@v4
     - name: Login to Azure 
       uses: azure/login@v2
       with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        environment: 'AzureCloud'
        enable-AzPSSession: false
     - name: Azure CLI -Deploy Bicep Files
       uses: Azure/CLI@v2
       with:
        inlineScript: |
          #!/bin/bash
          set -euo pipefail
          az deployment sub create \
            --name "${{ env.DEPLOYMENT_NAME }}-${{ env.DEPLOYMENT_SUFFIX }}" \
            --template-file ./infra/aks-bicep/main.bicep \
            --parameters ./infra/aks-bicep/parameters.json \
              rgName="${{ env.RESOURCE_GROUP }}" \
              location="${{ env.DEPLOYMENT_REGION }}" \
              vnetName="${{ env.VNET_NAME }}" \
              vmName="${{ env.VM_NAME }}" \
              fwName="${{ env.FIREWALL_NAME }}" \
              acrName="${{ env.ACR_NAME }}" \
              aksClusterName="${{ env.CLUSTER_NAME }}" \
            --location "${{ env.DEPLOYMENT_REGION }}"
          az postgres server create \
            --resource-group "${{ env.RESOURCE_GROUP }}" \
            --name "${{ env.DB_SERVER_NAME }}" \
            --location "${{ env.DEPLOYMENT_REGION }}" \
            --admin-user petclinicaksadmin \
            --admin-password petclinicAKS123** \
            --sku-name GP_Gen5_2

  build_Java_App: # Build the Java Application 
     runs-on: ubuntu-latest
     needs: hub_networking_AKS_Cluster
     steps:
     - name: Login to Azure 
       uses: azure/login@v2
       with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        environment: 'AzureCloud'
        enable-AzPSSession: false
     - name: checkout code
       uses: actions/checkout@v4
     - name: Set up JDK 11
       uses: actions/setup-java@v4
       with:
          java-version: '11'
          distribution: 'temurin'
     # Build Java Application    
     - name: Build with Maven, compile and build the Docker image
       run: |
        mvn spring-boot:build-image
     # Azure Powershell Cli - ACR Login, Tag Image, Push Image, Update ACR, Attach ACR to Cluster, Create Pod   
     - name: Azure Powershell Cli - ACR Login, Tag Image, Push Image
       uses: azure/powershell@v2
       with:
        inlineScript: |
         az acr login --name "${{ env.ACR_NAME }}"
         docker tag docker.io/library/spring-petclinic:2.7.0-SNAPSHOT "${{ env.ACR_NAME }}.azurecr.io/petclinic"
         docker push "${{ env.ACR_NAME }}.azurecr.io/petclinic"
        azPSVersion: "latest"
     - name: Set the target AKS cluster.
       uses: Azure/aks-set-context@v3
       with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.RESOURCE_GROUP }}
     - name: Azure Powershell Cli - Update ACR, Attach ACR to Cluster, Create Service and Expose the Pod
       uses: azure/powershell@v2
       with:
        inlineScript: |
         az aks get-credentials --resource-group "${{ env.RESOURCE_GROUP }}" --name "${{ env.CLUSTER_NAME }}"
         az aks update --resource-group="${{ env.RESOURCE_GROUP }}" --name="${{ env.CLUSTER_NAME }}" --attach-acr "${{ env.ACR_NAME }}"
         kubectl run petclinicaks --image="${{ env.ACR_NAME }}.azurecr.io/petclinic:latest"
         kubectl expose pod petclinicaks --type=LoadBalancer --port=80 --target-port=8080
         kubectl get pods -A
         kubectl get services -o=jsonpath='{.items[*].status.loadBalancer.ingress[0].ip}'
        azPSVersion: "latest"
     # Re-Build Java Application  
     - name: Re-Build Java Application
       uses: actions/checkout@v4
     - name: Set up JDK 11
       uses: actions/setup-java@v4
       with:
          java-version: '11'
          distribution: 'temurin'
     - name: Build with Maven, compile and build the Docker image
       run: |
        mvn spring-boot:build-image
    # Azure Powershell Cli - Get deployment IP Address   
     - name: Azure Powershell Cli - Get deployment IP Address 
       uses: azure/powershell@v2
       with:
        inlineScript: | 
         kubectl get service petclinicaks
         kubectl get services -o=jsonpath='{.items[*].status.loadBalancer.ingress[0].ip}'
        azPSVersion: "latest"
